###LIST PESSOA_UNIDADES
GET http://localhost:8000/api/pessoa_unidades
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

###VER PESSOA_UNIDADES
GET http://localhost:8000/api/pessoa_unidades/1
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

####ADICIONAR PESSOA_UNIDADES
POST http://localhost:8000/api/pessoa_unidades
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

{
    "nome":"Loren Epsun",
    "descritivo":"Loren Epsun",
    "cnpj":"Loren Epsun"

}
####MUDAR PESSOA_UNIDADES
POST http://localhost:8000/api/pessoa_unidades/1
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

{
    "_method": "PUT",
    "nome":"Loren Epsun",
    "descritivo":"Loren Epsun",
    "cnpj":"Loren Epsun"

}

####APAGAR PESSOA_UNIDADES
POST http://localhost:8000/api/pessoa_unidades/1
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

{
    "_method": "DELETE"
}
