###LIST PRODUTOS
GET http://localhost:8000/api/produtos
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

###VER PRODUTOS
GET http://localhost:8000/api/produtos/1
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

####ADICIONAR PRODUTOS
POST http://localhost:8000/api/produtos
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

{
    "nome":"Loren Epsun",
    "descritivo":"Loren Epsun",
    "produto_categoria_id":1,
    "ativo":1

}
####MUDAR PRODUTOS
POST http://localhost:8000/api/produtos/1
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

{
    "_method": "PUT",
    "nome":"Loren Epsun",
    "descritivo":"Loren Epsun",
    "produto_categoria_id":1,
    "ativo":1

}

####APAGAR PRODUTOS
POST http://localhost:8000/api/produtos/1
Authorization: Bearer :hash
Content-Type: application/json
Accept: application/json

{
    "_method": "DELETE"
}
